@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Collisionhandler",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_72851844 { 
   	label=Kugel
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Kugel72851844[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Kugel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   bildschirm: Bildschirm [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   kugel: Buntstift [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   radius: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tisch: Tisch [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ GetX(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ GetY(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ bewegeKugel()</TD></TR>
<TR><TD ALIGN="LEFT" >+ bounce(vcol: boolean)</TD></TR>
<TR><TD ALIGN="LEFT" >- center()</TD></TR>
<TR><TD ALIGN="LEFT" >+ collission(enemyX: double, enemyY: double)</TD></TR>
<TR><TD ALIGN="LEFT" >+ zeichneKugel()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_80817507 { 
   	label=Tisch
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Tisch80817507[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Tisch</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   height: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   rand: Buntstift [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   width: double [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ bewegeBis(x: double, y: double)</TD></TR>
<TR><TD ALIGN="LEFT" >+ zeichnen()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_983119864 { 
   	label=Collisionhandler
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Collisionhandler983119864[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Collisionhandler</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   radius: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   table: ArrayList&lt;Kugel&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Collisionhandler983119864 -> Kugel72851844[label="table
[0..*]"];
Kugel72851844 -> Tisch80817507[label="tisch
[0..1]"];
    
}
@enduml